ADS-6054: Adding more prebid events
themaven-net/Prebid.js pull request #57
Opened 2024-02-14 10:03 UTC by AritraSengupta

## Type of change

- [ ] Bugfix
- [ ] Feature
- [ ] New bidder adapter   
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes

- [ ] Does this change affect user-facing APIs or examples documented on http://prebid.org?
- [ ] Other

## Description of change

## Other information

2024-02-14 19:05 UTC, AritraSengupta commented
Tested this with @partha0solapurkar, we are able to get most of the stuff requested in the PR. Few things to note:
1. Floor price will be 0 if the it is not set on the bid level or the creative is not banner or video. Native ads will reflect a floor price 0.
2. I have added an `error` bid_status, to capture rejected bids by prebid.

2024-02-15 04:21 UTC, partha0solapurkar commented
> I have added an `error` bid_status, to capture rejected bids by prebid.

This is a great idea! @martiantim in my local testing for rejected bids, the only reason for rejection I saw was `bid does not meet price floor` and a bid amount and a bid response time were present. What do you think about collecting that data for the rejected bids along with the reason for rejection? 

Here are a few pros:

1. It would be useful if we suspect the floors are too high and want to analyze whether we have something to gain by lowering the floor. 

2. We can just reuse `bid_amountss` and `bid_response_timess` to record the numbers for the rejected bids in addition to the non-rejected bids. Currently they are 0 and null respectively for the rejected bids, so the only thing to keep in mind would be to filter on bid_status for some purposes. 

3. We don't need to add the reason for rejection to BQ as it is, but if we start collecting it, we can dig into the other reasons if there are any and later decide whether we want to add a summarized reason to BQ. 

I couldn't think of any cons. Can you think of any?

2024-02-15 07:40 UTC, AritraSengupta commented
@partha0solapurkar specifically for the bidRejected ones, do you think it will be helpful if we did the following:
1. send `error: {reason}` instead of just `error`
2. in the `bid_amounts`, I can send the cpm value from the bid rejected if it exists, so we will know the amount they bid at
@martiantim  thoughts?

2024-02-15 08:50 UTC, martiantim commented
Sounds great

Tim Martin

Vice President, Head of Engineering


Phone: +1 (510) 260-4175

Email: ***@***.*** ***@***.***>

Web: thearenagroup.net




On Wed, Feb 14, 2024 at 11:40 PM Aritra Sengupta ***@***.***>
wrote:

> @partha0solapurkar <https://github.com/partha0solapurkar> specifically
> for the bidRejected ones, do you think it will be helpful if we did the
> following:
>
>    1. send error: {reason} instead of just error
>    2. in the bid_amounts, I can send the cpm value from the bid rejected
>    if it exists, so we will know the amount they bid at
>    @martiantim <https://github.com/martiantim> thoughts?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/themaven-net/Prebid.js/pull/57#issuecomment-1945515534>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAN7LMOY3CINK4GMA3AHO3YTW3YVAVCNFSM6AAAAABDH7R7SCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNBVGUYTKNJTGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-02-15 16:14 UTC, partha0solapurkar commented
@AritraSengupta Yes, that sounds good to me. I'll dig into the error reasons first and then decide whether we need to send (a condensed version of) them to BigQuery, in case some of the reviewers are concerned about the size of the reason and the implications for storage costs.

2024-02-15 18:17 UTC, partha0solapurkar requested changes

2024-02-15 18:17 UTC, partha0solapurkar commented on modules/mavenDistributionAnalyticsAdapter.js
> +      bidAmount: bid.cpm || 0,
`Math.round((bid.cpm || 0) * 1000)`

2024-02-15 18:25 UTC, partha0solapurkar commented on modules/mavenDistributionAnalyticsAdapter.js
> +      bidResponseTime: null,
also, we should get the response time, since it's available and there's no downside to collecting it

2024-02-15 18:30 UTC, partha0solapurkar commented
LGTM based on local testing! I'll leave it up to you whether to get it reviewed for potential JS gotchas from people more familiar with JS 😄

2024-02-15 18:53 UTC, partha0solapurkar approved these changes

2024-02-15 19:17 UTC, merged

2024-02-16 18:49 UTC, partha0solapurkar commented
These were the frequencies of the bid status values I saw in half an hour: 
```
Map(
  "nobid" -> 6940189, 
  "error: Bid does not meet price floor" -> 19206, 
  "error: Bid has missing or invalid properties" -> 290, 
  "bid" -> 2436887, 
  "timeout" -> 43071
)
```
Based on this, I don't think it's necessary to condense bid status when recording it in BQ.

2024-02-16 19:02 UTC, partha0solapurkar commented
actually, I'll revisit these frequencies later because many users are still running the older (probably cached) code

2024-02-20 16:52 UTC, partha0solapurkar commented
By now more than 99% of the users are running the new code. These were the frequencies of the bid status values I saw in an hour:
```
{
  "nobid": 51171942,
  "error: Bid does not meet price floor": 139733,
  "error: Bid has missing or invalid properties": 1188,
  "bid": 23036449,
  "timeout": 490173
}
```
Based on this, I don't think it's necessary to condense bid status when recording it in BQ.

2024-02-21 19:14 UTC, martiantim commented
I like these numbers. 0.2% errors with almost all of them being an issue that the vendor probably needs to fix on their end. Good work!